### ISSUE TITLE
Uniqueness of identifiers

### ISSUE THREAD

**Issue by northernjamie** [OpenDataManchester/PPP#2]
Have we thought about how to ensure uniqueness of identifiers? If managed through the 'portal', then I guess that will do it, but is there an expectation that there may be other suppliers providing software that adheres to the standard, and if so - how do we ensure these things are globally unique?

**Comment by DsposalTom** [comment]
We talked about adding in an organisation code in the ID.  So for example:
open3p-odm-cont-09098
open3p-dsp-cont-09098
The governance organisation would be responsible for providing the organisation code.  In the same way that GS1 does for barcoding

**Comment by DsposalTom** [comment]
Talking more about this I think, because of privacy, the organisation code needs to be pseudonymised.

**Comment by DsposalTom** [comment]
Thinking and investigating more - can the standard use a [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier)?
