### ISSUE TITLE
'What is Open 3P standard' page refers to date in the past

### ISSUE THREAD

**Issue by northernjamie** [OpenDataManchester/PPP#30]
On the page below, we should remove the line "PPP has 5 main aims which will be delivered by 30th November 2022", and replace with something like "PPP's 5 main aims were to:"

https://opendatamanchester.github.io/PPP/1.1-alpha/1_Start_Here/1_1_Introduction/#what-is-the-open-3p

**Comment by DsposalTom** [comment]
Fixed in commit bd0b680
