### ISSUE TITLE
Correct typos in ERG diag on base materials page

### ISSUE THREAD

**Issue by northernjamie** [OpenDataManchester/PPP#33]
https://opendatamanchester.github.io/PPP/1.1-alpha/3_Data_Specification/3_1_Base_Materials/

attritubes -> attributes
contolled_lists -> controlled_lists

**Comment by northernjamie** [comment]
Also on materials page

**Comment by northernjamie** [comment]
And the components, complete packaging and load catalogue diags

**Comment by DsposalTom** [comment]
Fixed with [934570f](https://github.com/OpenDataManchester/PPP/commit/934570f713789c7c07a65ad8ee45eb222282cf21) commit
