### ISSUE TITLE
On materials page, I think this 'weightMaterial' should be 'materialWeight'

### ISSUE THREAD

**Issue by northernjamie** [OpenDataManchester/PPP#34]
![image](https://user-images.githubusercontent.com/19503373/225590984-ae51ee9b-a60b-4a72-b638-94de489723bf.png)

https://opendatamanchester.github.io/PPP/1.1-alpha/3_Data_Specification/3_2_Materials/#materials

**Comment by DsposalTom** [comment]
Fixed - will be live on the next release

**Comment by DsposalTom** [comment]
Fixed in commit [fe84cee](https://github.com/OpenDataManchester/PPP/commit/fe84cee45fd6566a9a9ba5c1b5e696cafd936845)
