### ISSUE TITLE
Link to certification source on Materials page 404s

### ISSUE THREAD

**Issue by northernjamie** [OpenDataManchester/PPP#35]
![image](https://user-images.githubusercontent.com/19503373/225591573-4cdcb7af-e993-47e6-991c-51cc4c0bd57b.png)

**Comment by DsposalTom** [comment]
Oh yeah I have having a nightmare with markdown and linking with the versioning.  I'm going to remove out the internal links until I can fix it.

**Comment by DsposalTom** [comment]
Fixed in commit [fe84cee](https://github.com/OpenDataManchester/PPP/commit/fe84cee45fd6566a9a9ba5c1b5e696cafd936845)
