### ISSUE TITLE
Add Open 3P branding to the standard

### ISSUE THREAD

**Issue by DsposalTom** [OpenDataManchester/PPP#61]
Should we add Open 3P branding to the mkdocs?

**Comment by Julianlstar** [comment]
Yes we should. What is needed? A banner?

**Comment by DsposalTom** [comment]
Yeah a banner would be good, most of what we need is in the style guidelines too.

[Material for MkDocs documentation](https://squidfunk.github.io/mkdocs-material/setup/) has some good information on how to change the look and feel so it shouldn't be that hard to do.
