### ISSUE TITLE
Various typo tweaks

### ISSUE THREAD

**Issue by DsposalTom** [OpenDataManchester/PPP#62]
**Introduction**

- [x] For consistency, we may want to rephrase in this section where we say ‘open data standard’ and instead use the term ‘open standard for packaging data’. 

**Key concepts** 

- [x] Should these be updated to reflect the end of life routes we now cover? Not just reuse and recycle? 

**Data flow** 

- [x] This whole section still uses the ‘component catalogue’ terminology and needs updating – as does the diagrams. 

**Data formats** 

- [ ] Text is out of date – shouldn’t say ‘plastic packaging portal’, probably should be ‘Open 3P’ 

**Components**

- [x] Just flagging the recycled content description here after our WRAP call – I think we do need to update this as it is specific about plastic here.

**Complete Packaging** 

- [x] Delete the word catalogue from here I think

**Load Catalogue** 

- [x] We say ‘tertiary’ here but that isn’t the word we use in the controlled list. 

**Load** 

- [x] We say ‘tertiary’ here but that isn’t the word we use in the controlled list. 

**Controlled lists – certificate source** 

- [x] I think we should add some text on this to say that if there are important industry certification sources not included please contact us to recommend their addition.

**Comment by DsposalTom** [comment]
Added now item
**Components**
Just flagging the recycled content description here after our WRAP call – I think we do need to update this as it is specific about plastic here.

**Comment by DsposalTom** [comment]
Sophie wanted more changes to
**Components**
Maybe we could change to ‘recommended’ and then in the description say “Percentage of recycled content included in the makeup of the component. It is ‘required’ for plastic packaging where for the purposes of this standard we refer to UK’s HM Revenue and Customs…” (rest same as is there now)

**Comment by Julianlstar** [comment]
Is this going to be a continuous typo issue thread or do we create separate issues for each tweak?

**Comment by DsposalTom** [comment]
@Julianlstar we need to be pragmatic really. It really depends at what point the issue is at.  If there is a branch made then we should create another issue.  If not then pile one.  Once a branch is made and a pull request raised this issue should close off automatically.

**Comment by DsposalTom** [comment]
@Julianlstar @northernjamie I think the [data formats page](http://standard.open3p.org/2.0/2_Data_Formats/2_1_Data_Formats/) needs a complete overhaul.
