### ISSUE TITLE
Tweak licence

### ISSUE THREAD

**Issue by DsposalTom** [OpenDataManchester/PPP#68]
Currently it says
The standard is open and free to use, copy and distribute. However, the standard is protected by the [Apache License, Version 2.0](../LICENCE.md){target=_blank} so you must use the correct attribution and licence.

Change it to say
The standard is open and free to use, copy and distribute. However, the standard is (C) Open Data Manchester CIC 2021-2023 and made available through the Apache License, Version 2.0 so you must use the correct attribution and licence.

**Comment by DsposalTom** [comment]
When you say "we need to work out" do you not want me to change it now and we talk about it in the future?

**Comment by Julianlstar** [comment]
I think we need to specify what is covered by the Apache licence - schema and what licence covers the documentation CC 4.0. Apache Licences are for code. CC licences for traditionally copyrightable material.
Leave it for now and will have a think about it.

**Comment by DsposalTom** [comment]
@Julianlstar any update?
