### ISSUE TITLE
Product Type Controlled List - typo and addition to list

### ISSUE THREAD

**Issue by ecosystem2** [OpenDataManchester/PPP#81]
typo: comestic > cosmetic

Review category list?
Medical products are exempt from plastic taxes 
Is there a need for this list to differentiate between healthcare related devices that are and are not exempt from taxes?

[definition of medical product](https://www.legislation.gov.uk/uksi/2012/1916/regulation/2/made)
[see attached gov guidance](https://www.gov.uk/guidance/check-which-plastic-packaging-is-exempt-from-plastic-packaging-tax#:~:text=Plastic%20packaging%20manufactured%20or%20imported,product%20when%20it%20is%20produced.)

**Comment by DsposalTom** [comment]
I'll fix the typo. I think the Medical products/ healthcare related products might have to go to the iSCB @Julianlstar because this feels it needs board discussion.
