### ISSUE TITLE
Introduction: Key Concepts

### ISSUE THREAD

**Issue by ecosystem2** [OpenDataManchester/PPP#84]
**No label on table and spacing too large above and below diagram**
_Add: this table can help you to visualise how information might flow across the packaging supply chain using Open 3P. The standard supports data exchange between necessary parties whilst preserving a single source of truth across the industry._

**Add to key concepts?**

UUID (this is expanded on in Section 4)
- a machine readable unique identifier generated for an entry conforming to the standard
- UUIDs improve data flow by assigning an unambiguous tag to your data
- these ids are then used to link between layers of the standard e.g. to link components to complete packaging

Single Source of Truth

**Comment by DsposalTom** [comment]
The padding/margin above and below is generated by the diagramming library mermaid.  I can have a look if I can reduce it but it might take some time. I'll work through the rest through
